name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: SSH and Deploy
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}

        run: |
          echo "$SSH_KEY" > key
          chmod 600 key
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          ssh -i key ubuntu@ec2-16-170-217-173.eu-north-1.compute.amazonaws.com "source startServer.sh"
