name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 644 ~/.ssh/known_hosts
          ssh-keyscan -H ec2-16-170-217-173.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}

        run: |
          echo "$SSH_KEY" > key
          chmod 600 key
          ssh -i key ubuntu@ec2-16-170-217-173.eu-north-1.compute.amazonaws.com "source startServer.sh"
